hw10_project/hw10_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

hw10_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<int:_id>/', views.author, name='author'),
    path('new_quote/', views.new_quote, name='new_quote'),
    path('new_author/', views.new_author, name='new_author'),
    path('new_tag/', views.new_tag, name='new_tag'),
]

hw10_project/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from .form import LoginForm
from .views import RegisterView

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html',), name='logout'),
]

hw10_project/quotes/models.py
from django.db import models

class Author (models.Model):
    fullname = models.CharField(max_length=50, null=False, unique=True)
    born_date = models.CharField(max_length=50, null=True)
    born_location = models.CharField(max_length=150, null=True)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.fullname}'


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quote}'

hw10_project/users/models.py
from django.db import models

# Create your models here.

hw10_project/quotes/views.py
from django.shortcuts import render, redirect

from django.core.paginator import Paginator
from .utils import get_mongodb
from .form import TagForm, AuthorForm, QuoteForm
from .models import Author, Quote
from pymongo import MongoClient

# Create your views here.


def main(request, page=1):

    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={"quotes":quotes_on_page})


def get_mongodb():
    client = MongoClient('mongodb://localhost')
    db = client.hw
    return db    


def author(request, _id):

    author = Author.objects.get(pk=_id)
    return render(request, "quotes/author.html", context={'author': author})


def new_author(request):

    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/new_author.html', context={'form': AuthorForm(), 'message': 'Form not valid'})
    return render(request, 'quotes/new_author.html', context={'form': AuthorForm()})


def new_quote(request):

    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/new_quote.html", context={'form': QuoteForm(), "message": "Form not valid"})
    return render(request, "quotes/new_quote.html", context={'form': QuoteForm()})


def new_tag(request):
    
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/new_tag.html", context={'form': TagForm(), "message": "Form not valid"})
    return render(request, "quotes/new_tag.html", context={'form': TagForm()})

hw10_project/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .form import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f"Hi {username}! Your account has been created.")
            return redirect(to="users:login")
        return render(request, self.template_name, {'form': form})

hw10_project/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p>
        <strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span>
        <span class="author-born-location">{{author.born_location}}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>
{% endblock %}

hw10_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css'%}">
    <title>HomeWork</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3" >
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="/users/logout" class="btn btn-light">Logout</a>
                    <a href="{% url 'quotes:new_quote' %}" class="btn btn-info">Add Quote</a>
                    <a href="{% url 'quotes:new_author' %}" class="btn btn-info">Add Author</a>
                    <a href="{% url 'quotes:new_tag' %}" class="btn btn-info">Add Tag</a>
                    {% else %}
                    
                    <a href="/users/signup" class="btn btn-light">Signup</a>
                    <a href="/users/signin" class="btn btn-light">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>
    
    

        {% block content %} {% endblock %}

    </div>
</body>
</html>

hw10_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html'%}
{% load extract%}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}

    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}
        
            
        </div>
    </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"><span
                            aria-hidden="true">←</span> Previous</a>
                </li>

                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next
                        <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>
</div>


{% endblock %}

hw10_project/quotes/templates/quotes/new_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:new_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born Date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born Location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw10_project/quotes/templates/quotes/new_quote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:new_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}</title>
</head>
<body>

</body>
</html>

hw10_project/quotes/templates/quotes/new_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:new_tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Tags:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw10_project/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}

<h3>Good bye</h3>

{% endblock %}

hw10_project/users/templates/users/signin.html
{% extends "quotes/base.html" %}
{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw10_project/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}